export const ORDERED_DIE_STATUS = 'ORDERED';
export const IN_STOCK_DIE_STATUS = 'IN-STOCK';
export const REPLACEMENT_ORDERED_DIE_STATUS = 'REPLACEMENT ORDERED';

export const dieStatuses = [
    ORDERED_DIE_STATUS,
    IN_STOCK_DIE_STATUS,
    REPLACEMENT_ORDERED_DIE_STATUS
];