const PRINTING_SETUP = 'PRINTING_SETUP';
const PRINTING = 'PRINTING';
const CUTTING_SETUP = 'CUTTING_SETUP';
const CUTTING = 'CUTTING';
const WINDING = 'WINDING';

module.exports.TIMER_TYPES = [ PRINTING_SETUP, PRINTING, CUTTING_SETUP, CUTTING, WINDING ];